### ISSUE TITLE
Maestro Integration ,Item Tracks

### ISSUE THREAD

**Issue by Seanny101** [chrisesharp/foundryvtt-owb#2]
I just tried out  Operation Whitebox ruleset with the Compendium Module .It looks very good. I normally use Maestro as well for most rulesets (for weapon sounds mostly). It seems the Hype Tracks (which introduce characters in the initiative tracker) work all good but Item Tracks ,at least for a weapon like the Rifle does not seem to work-unless I am doing something wrong (trying with preset characters from compendium pulled straight onto the map). Are the Item Tracks supported in this ruleset?

I also play with the OSE ruleset and the Item Tracks work properly there, even when a message first asks whether an attack is melee or missile, bit like here when a box asks to choose attack range.

Can you check this please -ruleset would benefit from having gunshot sounds in attacks ( I don't know how to add them unless I use Maestro Item tracks).

**Comment by chrisesharp** [comment]
Hi @Seanny101 thanks....I'd not tried Maestro before, so just had a play. After experimenting to try and recreate your problem, it seems that, for some reason, it didn't work unless I imported the NPC first. Once I'd done that, and added the gunshot as an Item Track to the rifle, it worked fine.

Do you know if it works with OSE dragging from the compendium straight onto the map?

**Comment by Seanny101** [comment]
Sorry took a while to respond 
.Just tried with actor imported from the compendium and all works OK.

Don't know what was going on initially -seems fine now.
All good-thanks for checking.
