### ISSUE TITLE
Increasing AC results is nothing happening

### ISSUE THREAD

**Issue by alcastilloa** [chrisesharp/foundryvtt-owb#3]
Hello, if using that setting, no roll takes place. FoundryVTT version: 0.8.9. 

Console log:

Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at Function.digestAttackResult (dice.js:135)
    at Function.sendAttackRoll (dice.js:199)
    at Object.callback (dice.js:350)
    at Dialog.submit (foundry.js:20673)
    at Dialog._onClickButton (foundry.js:20636)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
digestAttackResult @ dice.js:135
sendAttackRoll @ dice.js:199
callback @ dice.js:350
submit @ foundry.js:20673
_onClickButton @ foundry.js:20636
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

This is my first time doing it, apologies if improper. Thank you.

**Comment by chrisesharp** [comment]
Thanks for raising this...I'm not surprised if there is a bug as I never use AAC ;-) I'll check it out and let you know.

**Comment by chrisesharp** [comment]
Fixed in v1.0.9

**Comment by alcastilloa** [comment]
Fantastic, thank yo so much. My players are old schoolers 😉. Álvaro From: Chris SharpSent: Wednesday, September 1, 2021 1:20 PMTo: chrisesharp/foundryvtt-owbCc: alcastilloa; AuthorSubject: Re: [chrisesharp/foundryvtt-owb] Increasing AC results is nothing happening (#3) Fixed in v1.0.9—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  

	
        
		Virus-free. www.avast.com
