### ISSUE TITLE
V10 update

### ISSUE THREAD

**Issue by alcastilloa** [chrisesharp/foundryvtt-owb#4]
Would it be possible to update it to version 10 of foundry?

**Comment by chrisesharp** [comment]
Well, I was wondering if I was the only person who was still using this...but now I have the impetus to get on with it I will :-) 

I'll look at this in the New Year. Thanks for your interest!

**Comment by chrisesharp** [comment]
@alcastilloa I got a free day today, and have updated this to v1.2.0. If you update it in FoundryVTT it should work for V10. 
Take a look and let me know if you find any problems.
