### ISSUE TITLE
Reload macro not updating ammo

### ISSUE THREAD

**Issue by bapking** [chrisesharp/foundryvtt-owb#7]
Hi there. Firstly, the config is awesome, great work! I've found that the reload macro doesn't send any output to the chat that a character is reloading, nor does the ammo count subtract on the character sheet. I've tried this with a couple of different characters and weapons with different ammo types but haven't got any results.

Thanks!

**Comment by chrisesharp** [comment]
Thanks @bapking for the kind words. Re: the macro...that's odd, as it works for me. Is the ammo count decreasing when you fire the weapon?

Firstly, do you have the token selected of the character you are reloading? If so, then does it pop up a dialog asking which weapon you are reloading for that character?

To be honest, the reload macro isn't very clever. It just resets the ammo count in the ammo item to its maximum value. So you could just keep reloading and have a never ending supply of ammo, but it's really only meant to be a way of indicating a reload action rather than full automation.

**Comment by bapking** [comment]
I was a bit confused about the ammo count decreasing - it does actually do so when I fire. The macro doesn't seem to reset the clip to 10 or output in the chat, I've attached a video for reference. Maybe I'm doing something wrong and you'll be able to tell.

https://github.com/chrisesharp/foundryvtt-owb/assets/5245216/58c8cdda-91b2-48c7-8b8c-11c0c24030e5

**Comment by chrisesharp** [comment]
Hmm, that is odd. Could you switch on the Developer Tools and look at the console when you try that? I'm wondering if any errors are being output there. (Go up to the FoundryVTT menu and toggle them there, and look a the Console tab)

**Comment by bapking** [comment]
I don't see the option to toggle the tools in the menu, but I used the F12 key, hopefully it's correct. If not let me know.
[consoleoutput.txt](https://github.com/chrisesharp/foundryvtt-owb/files/13862979/consoleoutput.txt)

https://github.com/chrisesharp/foundryvtt-owb/assets/5245216/f342dc3c-94a3-4999-ac97-bcf3ac0b6c00

**Comment by chrisesharp** [comment]
Thanks...OK, can I check that you have the latest version (v1.3.4) and are running with FoundryVTT v11? I see errors in there referring to accessing `data` fields which were fixed way back in V10, so this is odd.

**Comment by bapking** [comment]
Versions are as follows;
Foundry: Version 11 Stable Build 315, 
WWII:OWB game system: 1.3.4
WWII:OWB OGL Content module: 1.0.9 
Ponteville Bridge game world: 1.0.2

**Comment by chrisesharp** [comment]
Figured it out! The macro pre-populated in the Ponteville Bridge world is an old back-level version of the macro! 

If you delete it from the macro bar, and re-import it from the macro compendium, it all works fine :-) 

I'll have to respin the world content and update it at some point.

**Comment by bapking** [comment]
That worked, thanks! Do you have a kofi or something? I'd like to make a contribution for your work!

**Comment by chrisesharp** [comment]
Wow, that's very kind of you. I do this just for the love of it, but you've prompted me to create a [ko-fi page](https://ko-fi.com/chrisesharp), as I've been thinking about it for a long while and never got around to it. No pressure to actually donate, though!
