### ISSUE TITLE
V12 Support

### ISSUE THREAD

**Issue by alcastilloa** [chrisesharp/foundryvtt-owb#8]
Hello, the new "scenes regions" feature is definitely something that will add a lot of tactical opportunities for this system.
Thank you.

**Comment by chrisesharp** [comment]
I'm just starting to go through my various systems to remediate base V12 support for them all. Will have to have a look at the scene region feature, as I haven't seen it yet.

**Comment by chrisesharp** [comment]
This should be implemented in the v1.4.1 release now. Try it out and let me know if you find any problems.
